<script src="{{ asset('frontend_asset/plugins/jquery/jquery-1.11.1.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/flexslider/jquery.flexslider.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/rs-plugin/js/jquery.themepunch.tools.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/rs-plugin/js/jquery.themepunch.revolution.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/selectbox/jquery.selectbox-0.1.3.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/pop-up/jquery.magnific-popup.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/animation/waypoints.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/count-up/jquery.counterup.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/animation/wow.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/animation/moment.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/calender/fullcalendar.min.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/owl-carousel/owl.carousel.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/timer/jquery.syotimer.js') }}"></script>
<script src="{{ asset('frontend_asset/plugins/smoothscroll/SmoothScroll.js') }}"></script>
<script src="{{ asset('frontend_asset/js/custom.js') }}"></script>
<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap.min.js"></script>
